name = "RegisterOptimize"
uuid = "b981a1b5-4587-53b0-9c3d-454c648f6f8d"
authors = ["Tim Holy <tim.holy@gmail.com>"]
version = "0.1.1"

[deps]
CachedInterpolations = "b9709bfb-d23d-5560-8276-8c35c4b76823"
CenterIndexedArrays = "46a7138f-0d70-54e1-8ada-fb8296f91f24"
CoordinateTransformations = "150eb455-5306-5404-9cee-2592286d6298"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathProgBase = "fdba3010-5040-5b88-9595-932c9decdf73"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
QuadDIRECT = "dae52e8d-d666-5120-a592-9e15c33b8d7a"
RegisterCore = "67712758-55e7-5c3c-8e85-dda1d7758434"
RegisterDeformation = "c19381b7-cf49-59d7-881c-50dfbd227eaf"
RegisterFit = "36121b08-3789-5198-aff2-59a3443d9b59"
RegisterMismatch = "3c0dd727-6833-5f5d-a1e8-c0d421935c74"
RegisterPenalty = "464fa2a9-b19c-5c59-8698-f58c971f971e"
RegisterUtilities = "d4862ba2-f42c-5aeb-af4f-96a8884a16c4"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[extras]
RegisterUtilities = "d4862ba2-f42c-5aeb-af4f-96a8884a16c4"
Rotations = "6038ab10-8711-5258-84ad-4b1120ba62dc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Rotations", "RegisterUtilities"]
